---
- name: Webhook rulebook example
  hosts: all 
  gather_facts: false
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5229
  rules:
    - name: Say Howdy
      condition: event.payload.message == "Howdy! Ansible EDA"
      action:
        debug:
